<center>
<a href="http://www.insa-toulouse.fr/" ><img src="http://www.math.univ-toulouse.fr/~besse/Wikistat/Images/logo-insa.jpg" style="float:left; max-width: 120px; display: inline" alt="INSA"/></a> 

<a href="http://wikistat.fr/" ><img src="http://www.math.univ-toulouse.fr/~besse/Wikistat/Images/wikistat.jpg" style="max-width: 250px; display: inline"  alt="Wikistat"/></a>

<a href="http://www.math.univ-toulouse.fr/" ><img src="http://www.math.univ-toulouse.fr/~besse/Wikistat/Images/logo_imt.jpg" style="float:right; max-width: 250px; display: inline" alt="IMT"/> </a>
</center>

# <a href="https://cran.r-project.org/"><img src="https://cran.r-project.org/Rlogo.svg" style="max-width: 40px; display: inline" alt="R"/></a> [pour Statistique et Science des Données](https://github.com/wikistat/Intro-Python)

# Introduction à <a href="https://cran.r-project.org/"><img src="https://cran.r-project.org/Rlogo.svg" style="max-width: 40px; display: inline" alt="R"/></a>

**Résumé** Tutoriel d'initiation qui précise l'environnement de travail (packages, répertoire courant). Il propose de manipuler les différents types d'objets  existants dans R et décrit quelques outils d'importation/exportation de données. 

## 1 Environnement
Quelques compléments pour une utilisation facile concernant le chargement de librairies complémentaires et le répertoire de travail.
### 1.1 Librairies
La liste complète des *packages* ou librairies disponibles est consultable sur le site du [CRAN](http://cran.cict.fr/web/packages/index.html).  L'installation d'un package supplémentaire peut se faire via le menu de Rstudio `Packages>Installer le(s) package(s)` et en choisissant un site miroir du CRAN ou directement avec la fonction `install.packages("nomPackage")`. Celui-ci est installé dans un répertoire de l'utilisateur qui n'a donc pas besoin de dorits d'administration de la machine.
### 1.2 Répertoire courant
Pour pouvoir récupérer des données, il est utile de connaître le répertoire de travail, c'est-à-dire le répertoire sous lequel les divers résultats seront sauvegardés par défaut. Ce dernier s'obtient à l'aide la commande:

In [1]:
getwd()

[1] "/home/ltduong/Bureau/4GMM/TP_exploration/Intro-R-master"

Tandis que la commande 

`setwd("C:/User/Mes documents/CoursR")`

change de répertoire courant. C'est également possible à partir du menu de RStudio (`Set Sorking Directory`).

## 2 Structures de données
Sous R, les éléments de base sont des objets : vecteurs, matrices, listes..., sur lesquels sont appliquées des fonctions qui fournissent des résultats numériques et graphiques. Ces objets se différencient par leur *mode* décrivant leur contenu, et leur *classe* décrivant leur structure. Les objets atomiques sont de mode *homogène* et les objets récursifs (listes) sont de mode *hétérogène*. 

Les différents modes sont `null` (objet vide), `logical, numeric, complex, character`. Les classes d'objets les plus courantes sont : `vector, matrix, array, factor, data.frame, list`. 

On peut avoir des vecteurs, matrices, tableaux, ... de mode `null` (objet vide), `logical` (`TRUE, FALSE, NA`), `numeric, complex`, character tandis que les listes et les *data frame* peuvent être composés d'éléments hétérogènes.

**Attention** Une confusion entre classes d'objets dans l'appel d'une fonction est la source d'erreur largement la plus fréquente. 
### 2.1 Opérations sur les scalaires
Entrer les commandes en identifiant  les différents types de données

In [3]:
2+2

[1] 4

In [4]:
exp(10)

[1] 22026.47

In [5]:
a = log(2)
b <- cos(10) #  "<-" est équivalent à "="
a+b

[1] -0.1459243

In [6]:
a

[1] 0.6931472

In [7]:
b

[1] -0.8390715

In [8]:
2==3

[1] FALSE

In [9]:
b = 2<3 ; b

[1] TRUE

In [10]:
ls()  # variables de l'environnement de travail

[1] "a" "b"

In [11]:
rm(a) # effacer une ou plusieurs variables

In [12]:
a

ERROR: Error in eval(expr, envir, enclos): objet 'a' introuvable


In [13]:
a="texte"
a

[1] "texte"

### 2.2 Type caractère
Manipulation de Chaînes de caractères.

In [14]:
c="ABCdef";nchar(c);c

[1] 6

[1] "ABCdef"

In [15]:
is.character(c)

[1] TRUE

In [16]:
substr(c,1,3)

[1] "ABC"

In [17]:
# changer la casse
tolower(c)

[1] "abcdef"

In [18]:
toupper(c)

[1] "ABCDEF"

In [19]:
# coller
paste("alpha",c,sep="-")

[1] "alpha-ABCdef"

### 2.3 Type booléen et opérateurs logiques
Les variables booléennes prennent les valeurs `TRUE` ou `FALSE` ; les opérateurs de comparaison  `<,> <=, >=, !=, ==` retournent ces valeurs tandis  que `&, |, !` sont les opérateurs logiques "et", "ou", "non". 

In [20]:
a = 3 ; b = 6
a<=b

[1] TRUE

In [21]:
a!=b

[1] TRUE

In [22]:
(b - 3 == a) & ( b>= a)

[1] TRUE

In [23]:
(b  == a) | (b>=a)

[1] TRUE

### 3.4 Les vecteurs (`vector`)
Un vecteur regroupe des éléments de même mode. La création d'un vecteur peut se faire par la commande `c(e1,e2,...)`. On peut également générer une séquence avec la commande `seq(a,b,t)` débutant par `a` inférieure ou égale à `b` et de pas `t` ; `rep(x,n)` est un vecteur répétant *n* fois l'élément `x`.

In [43]:
d = c(2,3,5,8,4,6); d
is.vector(d)

[1] 2 3 5 8 4 6

[1] TRUE

In [44]:
c(2,5,"texte")

[1] "2"     "5"     "texte"

Séquences et répétitions.

In [45]:
1:10 

[1]  1  2  3  4  5  6  7  8  9 10

In [46]:
seq(from=1,to=20,by=2)

[1]  1  3  5  7  9 11 13 15 17 19

In [47]:
seq(1,20,by=5)

[1]  1  6 11 16

In [48]:
seq(1,20,length=5)

[1]  1.00  5.75 10.50 15.25 20.00

In [49]:
rep(5,times=10)

[1] 5 5 5 5 5 5 5 5 5 5

In [50]:
rep(c(1,2),3)

[1] 1 2 1 2 1 2

In [51]:
rep(c(1,2),each=3)

[1] 1 1 1 2 2 2

In [52]:
e = rep(1,10); e

[1] 1 1 1 1 1 1 1 1 1 1

Extraction dans un vecteur par `[]` et valeurs manquantes.

In [53]:
d[2];d[2:3];d[-3];d[-4];d

[1] 3

[1] 3 5

[1] 2 3 8 4 6

[1] 2 3 5 4 6

[1] 2 3 5 8 4 6

In [54]:
# attention aux indices :
d[-1:2];d[-(1:2)] 

ERROR: Error in d[-1:2]: les indices négatifs ne peuvent être mélangés qu'à des 0


[1] 5 8 4 6

In [56]:
# NA (Not Available) signale une donnée manquante
d[4] = NA ;d;summary(d)

[1]  2  3  5 NA  4  6

   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's 
      2       3       4       4       5       6       1 

In [57]:
is.na(d);help(NA)

[1] FALSE FALSE FALSE  TRUE FALSE FALSE

In [58]:
# fonctions "any = existence" et "all = tout"
any(is.na(d));all(is.na(d))

[1] TRUE

[1] FALSE

Labels et opérations.

In [59]:
f = c(a=12,b=26,c=32,d=41);f
names(f);f["a"]

a  b  c  d 
12 26 32 41

[1] "a" "b" "c" "d"

a 
12

In [60]:
names(f)=c("a1","a2","a3","a4")
f>30;f[f>30]  # noter les différences

a1    a2    a3    a4 
FALSE FALSE  TRUE  TRUE

a3 a4 
32 41

In [62]:
which(f>30) #indices
f[3]

a3 a4 
 3  4

a3 
32

In [63]:
f[2] = 22;f+100;f+d  # un problème de dimension

a1  a2  a3  a4 
112 122 132 141

Warning message in f + d:
“la taille d'un objet plus long n'est pas multiple de la taille d'un objet plus court”

[1] 14 25 37 NA 16 28

In [64]:
cos(f);length(f);sum(f)

a1         a2         a3         a4 
 0.8438540 -0.9999608  0.8342234 -0.9873393

[1] 4

[1] 107

In [65]:
t(f) # transposition

a1 a2 a3 a4
[1,] 12 22 32 41

In [67]:
e=rep(2,4);e; 2*e; 2+e

[1] 2 2 2 2

[1] 4 4 4 4

[1] 4 4 4 4

In [68]:
e+f ; e*f # opérations terme à terme

a1 a2 a3 a4 
14 24 34 43

a1 a2 a3 a4 
24 44 64 82

In [70]:
t(f)%*%e # produit scalaire
f%*%e

[,1]
[1,] 214

[,1]
[1,] 214

In [71]:
a <- c(3,-1,5,2,-7,3,9)
abs(a);sort(a);
order(a) #indices 

[1] 3 1 5 2 7 3 9

[1] -7 -1  2  3  3  5  9

[1] 5 2 4 1 6 3 7

3.5 Facteurs
Un facteur est un vecteur avec une liste prédéfinie de valeurs, les niveaux (\emph{levels}). Cela correspond typiquement à une variable qualitative nominale.

In [72]:
vect=c("a","b","c","b","b","a")
vect

[1] "a" "b" "c" "b" "b" "a"

In [74]:
vect.f=as.factor(vect)
vect.f

[1] a b c b b a
Levels: a b c

In [75]:
as.integer(vect.f)

[1] 1 2 3 2 2 1

In [76]:
as.character(vect.f)

[1] "a" "b" "c" "b" "b" "a"

### 3.6 Les matrices (`matrix`)
Comme les vecteurs, les matrices sont de mode quelconque mais ne
contiennent que des éléments de même nature. Pour créer une matrice, on utilise
la commande `matrix(vec,nrow=n,ncol=p)` où `vec` est le vecteur
contenant les éléments de la matrice de taille *n* par *p*, qui seront rangés en
colonne sauf si l'option `byrow=T` est utilisée.

In [77]:
A = matrix(1:15,ncol=5);A
B = matrix(1:15,nc=5,byrow=T)
B2=B;B2[1,1]="toto";B2

[,1] [,2] [,3] [,4] [,5]
[1,] 1    4    7    10   13  
[2,] 2    5    8    11   14  
[3,] 3    6    9    12   15

[,1] [,2] [,3] [,4] [,5]
[1,] toto 2    3    4    5   
[2,] 6    7    8    9    10  
[3,] 11   12   13   14   15

In [78]:
cbind(A,B);rbind(A,B) # concaténations

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
[1,] 1    4    7    10   13    1    2    3    4    5   
[2,] 2    5    8    11   14    6    7    8    9   10   
[3,] 3    6    9    12   15   11   12   13   14   15

[,1] [,2] [,3] [,4] [,5]
[1,]  1    4    7   10   13  
[2,]  2    5    8   11   14  
[3,]  3    6    9   12   15  
[4,]  1    2    3    4    5  
[5,]  6    7    8    9   10  
[6,] 11   12   13   14   15

In [79]:
A[1,3];A[,2];B[2,] # composants

[1] 7

[1] 4 5 6

[1]  6  7  8  9 10

In [80]:
A[1:3,2:4]

[,1] [,2] [,3]
[1,] 4    7    10  
[2,] 5    8    11  
[3,] 6    9    12

Opérations sur les matrices

In [83]:
g = seq(0,1,length=20)
C = matrix(g,nrow=4)
dim(C)

[1] 4 5

In [85]:
C;
C[C[,1]>0.1,]  # * voir question ci-dessous

[,1]       [,2]      [,3]      [,4]      [,5]     
[1,] 0.00000000 0.2105263 0.4210526 0.6315789 0.8421053
[2,] 0.05263158 0.2631579 0.4736842 0.6842105 0.8947368
[3,] 0.10526316 0.3157895 0.5263158 0.7368421 0.9473684
[4,] 0.15789474 0.3684211 0.5789474 0.7894737 1.0000000

[,1]      [,2]      [,3]      [,4]      [,5]     
[1,] 0.1052632 0.3157895 0.5263158 0.7368421 0.9473684
[2,] 0.1578947 0.3684211 0.5789474 0.7894737 1.0000000

In [86]:
# ranunif : tirage aléatoire uniforme
D = matrix(runif(16),ncol=4)
D>0.5

[,1]  [,2]  [,3]  [,4] 
[1,]  TRUE FALSE  TRUE FALSE
[2,]  TRUE FALSE  TRUE  TRUE
[3,] FALSE FALSE FALSE  TRUE
[4,] FALSE  TRUE  TRUE  TRUE

In [91]:
D[D[,1]>0.5,2]=0 
D# ** voir question ci-dessous

[,1]      [,2]      [,3]      [,4]      
[1,] 0.6813693 0.0000000 0.8195119 0.06763874
[2,] 0.9588778 0.0000000 0.9187148 0.89429445
[3,] 0.2420340 0.4552378 0.1439101 0.76774210
[4,] 0.2488665 0.6102864 0.6704543 0.50245170

In [92]:
A+B;A*B  #  opérations terme à terme

[,1] [,2] [,3] [,4] [,5]
[1,]  2    6   10   14   18  
[2,]  8   12   16   20   24  
[3,] 14   18   22   26   30

[,1] [,2] [,3] [,4] [,5]
[1,]  1    8    21   40   65 
[2,] 12   35    64   99  140 
[3,] 33   72   117  168  225

In [93]:
cos(A); cos(A[1:2,1:2])

[,1]       [,2]       [,3]       [,4]         [,5]      
[1,]  0.5403023 -0.6536436  0.7539023 -0.839071529  0.9074468
[2,] -0.4161468  0.2836622 -0.1455000  0.004425698  0.1367372
[3,] -0.9899925  0.9601703 -0.9111303  0.843853959 -0.7596879

[,1]       [,2]      
[1,]  0.5403023 -0.6536436
[2,] -0.4161468  0.2836622

In [94]:
# inversion
solve(A);solve(A[1:2,1:2])

ERROR: Error in solve.default(A): 'a' (3 x 5) doit être carrée


[,1]       [,2]      
[1,] -1.6666667  1.3333333
[2,]  0.6666667 -0.3333333

In [97]:
# produit matriciel
t(A) %*% B

[,1] [,2] [,3] [,4] [,5]
[1,]  46   52   58   64   70 
[2,] 100  115  130  145  160 
[3,] 154  178  202  226  250 
[4,] 208  241  274  307  340 
[5,] 262  304  346  388  430

In [98]:
A[1:2,1:2] %*% B[1:2,1:3]

[,1] [,2] [,3]
[1,] 25   30   35  
[2,] 32   39   46

In [99]:
t(B); 
diag(A) #vecteur contenant les termes diag

[,1] [,2] [,3]
[1,] 1     6   11  
[2,] 2     7   12  
[3,] 3     8   13  
[4,] 4     9   14  
[5,] 5    10   15

[1] 1 5 9

In [100]:
apply(A,2,sum)   # *** voir question ci-dessous

[1]  6 15 24 33 42

In [101]:
apply(D,1,max)

[1] 0.8195119 0.9588778 0.7677421 0.6704543

In [103]:
# Eléments propres
s=eigen(A[1:2,2:3])
s
s$values

eigen() decomposition
$values
[1] 12.244998 -0.244998

$vectors
           [,1]       [,2]
[1,] -0.6472056 -0.8550584
[2,] -0.7623155  0.5185316


[1] 12.244998 -0.244998

In [104]:
s$vectors #deja normalise et orth

[,1]       [,2]      
[1,] -0.6472056 -0.8550584
[2,] -0.7623155  0.5185316

**Questions**

- Que font {`rbind`} et {`cbind`}?
- Décortiquer la ligne ci-dessus marquée `*` et décrire ce qu'elle fait.
- Même chose avec `**`. 
- Que renvoie la ligne `***`? 


**Réponses**

- `rbind` et `cbind` collent deux vecteurs ou matrices respectivement en ligne ou en colonne.
- `C[C[,1]>0.1,]` peut se décomposer ainsi:
	- `C[,1]` extrait la première colonne de la matrice `C`
	- `C[,1]>0.1` renvoie un vecteur logique de longueur le nombre de lignes de C contenant `TRUE` si la valeur est supérieure à 0.1 et `FALSE` sinon.
	- `C[C[,1]>0.1,]` extrait de la matrice `C` les lignes où les éléments sur la première colonne sont supérieurs à 0.1 et toutes les colonnes si rien après la virgule.
- `**` extrait de la colonne 2 de la matrice `D`, les lignes où l'élément sur la première colonne est supérieur à 0.5 et met à 0 ces éléments.
- `***` renvoie un vecteur de longueur 5 (le nombre de colonnes de `A`) dont chaque élément est la somme des éléments d'une colonne de A.

**Noter** l'importance de ces différentes "astuces" pour éviter des boucles `for` dont l'*usage est fortement déconseillé* avec un langage interprété sous peine de plomber les temps d'exécution.

### 3.6 Les tableaux (`array`)
Les tableaux sont des matrices de dimensions supérieures à 2. On peut les générer à partir de la commande `array(vec,c(n,p,q,...))` où `vec` est le vecteur contenant les éléments du tableau et l'argument `c(n,p,q,...)` désigne les dimensions du tableau : *n* lignes, *p* colonnes, *q* matrices, ...

In [105]:
array(c(1:8, rep(1,8),seq(0,1,len=8)), dim = c(2,4,3))
E = .Last.value
E[, , 1]

, , 1

     [,1] [,2] [,3] [,4]
[1,]    1    3    5    7
[2,]    2    4    6    8

, , 2

     [,1] [,2] [,3] [,4]
[1,]    1    1    1    1
[2,]    1    1    1    1

, , 3

          [,1]      [,2]      [,3]      [,4]
[1,] 0.0000000 0.2857143 0.5714286 0.8571429
[2,] 0.1428571 0.4285714 0.7142857 1.0000000

[,1] [,2] [,3] [,4]
[1,] 1    3    5    7   
[2,] 2    4    6    8

In [106]:
dim(E);length(E);nrow(E);ncol(E)

[1] 2 4 3

[1] 24

[1] 2

[1] 4

In [107]:
E+10

, , 1

     [,1] [,2] [,3] [,4]
[1,]   11   13   15   17
[2,]   12   14   16   18

, , 2

     [,1] [,2] [,3] [,4]
[1,]   11   11   11   11
[2,]   11   11   11   11

, , 3

         [,1]     [,2]     [,3]     [,4]
[1,] 10.00000 10.28571 10.57143 10.85714
[2,] 10.14286 10.42857 10.71429 11.00000

In [116]:
H=array(1:12,c(2,3,2))
dim(H)
H
apply(H,1,mean)
?apply

[1] 2 3 2

, , 1

     [,1] [,2] [,3]
[1,]    1    3    5
[2,]    2    4    6

, , 2

     [,1] [,2] [,3]
[1,]    7    9   11
[2,]    8   10   12

[1] 6 7

In [112]:
apply(H,2,mean)

[1] 4.5 6.5 8.5

In [113]:
apply(H,3,mean)

[1] 3.5 9.5

**Questions**

- Expliquer les résulats des 3 appels à la fonction `apply()`.
- Créer un `array` à 4 dimensions et calculer la somme des éléments dans toutes les dimensions.


**Réponses**

- Dans le premier cas, on calcule la moyenne de tous les éléments ligne par ligne. Les éléments de la ligne 1 sont tous les élements de la tranche supérieure horizontale du parallélépipède `H` (1,3,5,7,9,11) ; de la tranche inférieure pour la ligne 2 (2,4,6,8,10,12). Dans le deuxième cas, le calcul est effectué colonne par colonne, le vecteur résultat est donc de longueur 3 ; il contient la moyenne des éléments des 3 tranches verticales (gauche - [1,2,7,8], centre - [3,4,9,10] et droite - [5,6,11,12]). Dans le troisième cas, le calcul de moyenne est fait sur les 2 tranches verticales "avant" (1,2,3,4,5,6) et "arrière" (7,8,9,10,11,12).
- Code:

In [ ]:
H2=array(1:24,c(2,3,2,2)) # crée un array à 4 dimensions équivalent dans cet exemple à 2 tableaux H 
apply(H,1,sum)
apply(H,2,sum)
apply(H,3,sum)
apply(H,4,sum)

### 3.7 Les listes (`list`)
Une liste est une collection ordonnée d'objets qui peuvent être de classes différentes. Les listes sont en particulier utilisées par certaines fonctions (cf. tutoriel "Programmation") pour renvoyer des résultats complexes sous forme
d'un seul objet. On utilise la fonction `list(nom1=el1,nom2=el2,...)` pour générer une liste. On peut accéder à chaque élément de la liste à l'aide de son index entre double crochets `[[...]]`, ou par son nom précédé du signe `$`.

In [117]:
x = list("toto",1:8);x
x[[1]];x[[1]]+1;x[[2]]+10 # *

[[1]]
[1] "toto"

[[2]]
[1] 1 2 3 4 5 6 7 8

[1] "toto"

ERROR: Error in x[[1]] + 1: argument non numérique pour un opérateur binaire


[1] "toto"

[1] 11 12 13 14 15 16 17 18

In [118]:
y = list(matrice=D,vecteur=f,texte="toto",scalaire=8)
names(y);y[[1]]

[1] "matrice"  "vecteur"  "texte"    "scalaire"

[,1]      [,2]      [,3]      [,4]      
[1,] 0.6813693 0.0000000 0.8195119 0.06763874
[2,] 0.9588778 0.0000000 0.9187148 0.89429445
[3,] 0.2420340 0.4552378 0.1439101 0.76774210
[4,] 0.2488665 0.6102864 0.6704543 0.50245170

In [119]:
y$matrice;y$vec

[,1]      [,2]      [,3]      [,4]      
[1,] 0.6813693 0.0000000 0.8195119 0.06763874
[2,] 0.9588778 0.0000000 0.9187148 0.89429445
[3,] 0.2420340 0.4552378 0.1439101 0.76774210
[4,] 0.2488665 0.6102864 0.6704543 0.50245170

a1 a2 a3 a4 
12 22 32 41

In [120]:
y[c("texte","scal")] # **

ERROR while rich displaying an object: Error in vapply(seq_along(mapped), function(i) {: les valeurs doivent être d'une longueur 1,
 mais FUN(X[[2]]) a une longueur 0

Traceback:
1. FUN(X[[i]], ...)
2. tryCatch(withCallingHandlers({
 .     rpr <- mime2repr[[mime]](obj)
 .     if (is.null(rpr)) 
 .         return(NULL)
 .     prepare_content(is.raw(rpr), rpr)
 . }, error = error_handler), error = outer_handler)
3. tryCatchList(expr, classes, parentenv, handlers)
4. tryCatchOne(expr, names, parentenv, handlers[[1L]])
5. doTryCatch(return(expr), name, parentenv, handler)
6. withCallingHandlers({
 .     rpr <- mime2repr[[mime]](obj)
 .     if (is.null(rpr)) 
 .         return(NULL)
 .     prepare_content(is.raw(rpr), rpr)
 . }, error = error_handler)
7. mime2repr[[mime]](obj)
8. repr_html.list(obj)
9. repr_list_generic(obj, "html", "\t<li>%s</li>\n", "\t<dt>$%s</dt>\n\t\t<dd>%s</dd>\n", 
 .     "<strong>$%s</strong> = %s", "<ol>\n%s</ol>\n", "<dl>\n%s</dl>\n", 
 .     numeric_item = "\t<dt

$texte
[1] "toto"

$<NA>
NULL


In [121]:
y[c("texte","scalaire")]

$texte
[1] "toto"

$scalaire
[1] 8

In [122]:
length(y);length(y$vecteur)

[1] 4

[1] 4

In [123]:
cos(y$scalaire)+y[[2]][1]

a1 
11.8545

In [124]:
summary(y)

         Length Class  Mode     
matrice  16     -none- numeric  
vecteur   4     -none- numeric  
texte     1     -none- character
scalaire  1     -none- numeric  

**Questions**

- Quel est le problème avec la ligne * ?
- Et avec la ligne ** ?


**Réponses**

- C'est la 2ème commande de la ligne qui renvoie une erreur. On cherche à ajouter 1 à un élément qui n'est pas numérique.
- Aucun composant de la liste ne s'appelle `scal` ("lettre à lettre"). 


### 3.8 Tableau de données (`data.frame`)
Un *data frame* est analogue à une matrice dont les colonnes peuvent être *hétérogènes*. Un *tableau de données* est un ensemble de vecteurs, une *liste*, rangés colonne par colonne, chaque colonne correspondant à une variable, chaque ligne à un individu. Le type *data frame* est très important, c'est **la façon** de gérer les données à étudier sous R lors d'une étude statistique.

Un tableau de données, est créé en regroupant des variables (vecteurs) de même longueur à l'aide de la commande  `data.frame(nom1=var1,nom2=var2,...)`. Une matrice est transformée en un tableau de données en utilisant la commande `as.data.frame(mat)`. 

In [125]:
taille = runif(12,150,180)
masse = runif(12,50,90)
sexe = rep(c("M","F","F","M"),3)

H = data.frame(taille,masse,sexe)
H

taille   masse    sexe
1  172.3511 69.23876 M   
2  162.5740 69.55682 F   
3  172.2135 87.82627 F   
4  152.5294 78.33130 M   
5  158.1337 61.83931 M   
6  160.8500 57.96665 F   
7  160.1103 60.18595 F   
8  177.6136 80.45405 M   
9  160.0898 73.27136 M   
10 176.0607 75.55829 F   
11 156.1821 85.64441 F   
12 178.4701 80.21109 M

In [126]:
summary(H)

     taille          masse       sexe 
 Min.   :152.5   Min.   :57.97   F:6  
 1st Qu.:159.6   1st Qu.:67.39   M:6  
 Median :161.7   Median :74.41        
 Mean   :165.6   Mean   :73.34        
 3rd Qu.:173.3   3rd Qu.:80.27        
 Max.   :178.5   Max.   :87.83        

In [127]:
# analogies entre data.frame, list et matrix
H[1,];H$taille;H$sexe

taille   masse    sexe
1 172.3511 69.23876 M

[1] 172.3511 162.5740 172.2135 152.5294 158.1337 160.8500 160.1103 177.6136
 [9] 160.0898 176.0607 156.1821 178.4701

[1] M F F M M F F M M F F M
Levels: F M

In [128]:
is.data.frame(H); is.matrix(H)

[1] TRUE

[1] FALSE

In [129]:
MH = as.matrix(H)
summary(MH)

      taille       masse   sexe 
 152.5294:1   57.96665:1   F:6  
 156.1821:1   60.18595:1   M:6  
 158.1337:1   61.83931:1        
 160.0898:1   69.23876:1        
 160.1103:1   69.55682:1        
 160.8500:1   73.27136:1        
 (Other) :6   (Other) :6        

In [130]:
as.list(H)

$taille
 [1] 172.3511 162.5740 172.2135 152.5294 158.1337 160.8500 160.1103 177.6136
 [9] 160.0898 176.0607 156.1821 178.4701

$masse
 [1] 69.23876 69.55682 87.82627 78.33130 61.83931 57.96665 60.18595 80.45405
 [9] 73.27136 75.55829 85.64441 80.21109

$sexe
 [1] M F F M M F F M M F F M
Levels: F M

In [131]:
rm(taille);taille # (1)

ERROR: Error in eval(expr, envir, enclos): objet 'taille' introuvable


In [132]:
H$taille

[1] 172.3511 162.5740 172.2135 152.5294 158.1337 160.8500 160.1103 177.6136
 [9] 160.0898 176.0607 156.1821 178.4701

In [133]:
attach(H);taille  # (2)

The following objects are masked _by_ .GlobalEnv:

    masse, sexe



[1] 172.3511 162.5740 172.2135 152.5294 158.1337 160.8500 160.1103 177.6136
 [9] 160.0898 176.0607 156.1821 178.4701

In [134]:
search()          # (3)

[1] ".GlobalEnv"        "H"                 "jupyter:irkernel" 
 [4] "package:stats"     "package:graphics"  "package:grDevices"
 [7] "package:utils"     "package:datasets"  "package:methods"  
[10] "Autoloads"         "package:base"

In [135]:
detach();taille   # (4)

ERROR: Error in eval(expr, envir, enclos): objet 'taille' introuvable


**Questions**

- Tester la fonction `summary` sur d'autres types d'objets.
- Quel est l'effet de la conversion "forcée" du `data.frame` en matrice opérée par la fonction `as.matrix()`?
- Commenter l'enchaînement des lignes 1 à 4. Quel est l'effet de la fonction `attach`? De la fonction `search`? De la fonction `detach`?
- Extraire la masse des individus dont la taille est supérieure à 160. 
- Extraire la masse et le sexe de ces mêmes individus.
- Extraire la taille des individus de sexe masculin dont la masse est inférieure à 70. C'est possible en une seule ligne (voir l'opérateur `&`, `help("&")`).


**Réponses**

In [136]:
# 1. Fonction summary
vec=c(2,5,3,6,5,4,1,8);summary(vec)
mat=matrix(1:20,nc=4,nr=5)
summary(mat);summary(c(mat))

   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
   1.00    2.75    4.50    4.25    5.25    8.00 

       V1          V2           V3           V4    
 Min.   :1   Min.   : 6   Min.   :11   Min.   :16  
 1st Qu.:2   1st Qu.: 7   1st Qu.:12   1st Qu.:17  
 Median :3   Median : 8   Median :13   Median :18  
 Mean   :3   Mean   : 8   Mean   :13   Mean   :18  
 3rd Qu.:4   3rd Qu.: 9   3rd Qu.:14   3rd Qu.:19  
 Max.   :5   Max.   :10   Max.   :15   Max.   :20  

   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
   1.00    5.75   10.50   10.50   15.25   20.00 

2. La conversion en matrice implique que tous les éléments sont désormais du mode `character`. La fonction `summary()` ne calcule plus des indicateurs numériques pour les colonnes `taille` et `masse`.
3. Enchaînement des lignes
	- (1) Supprime l'objet `taille` dans l'espace de travail courant ; l'objet `taille` n'est plus reconnu.
	- (2) Attache le data.frame `H` ; les composants de `H` deviennent accessibles directement.
	- (3) `search()` permet de lister les environnements liés à l'espace de travail courant.
	- (4) Détache l'environnement en position 2 dans la liste de `search()`.

In [137]:
# 4.
H[H$taille>160,2]  

[1] 69.23876 69.55682 87.82627 57.96665 60.18595 80.45405 73.27136 75.55829
[9] 80.21109

In [138]:
# 5.
H[H$taille>160,2:3]  

masse    sexe
1  69.23876 M   
2  69.55682 F   
3  87.82627 F   
6  57.96665 F   
7  60.18595 F   
8  80.45405 M   
9  73.27136 M   
10 75.55829 F   
12 80.21109 M

In [139]:
# 6.
H[H$masse<70 & H$sexe=="M",1]

[1] 172.3511 158.1337

## 4 Entrée / Sortie

### 4.1 Importation d'un jeu de données

`Tab1 = read.table("Tableau.dat")` lit le fichier nommé `Tableau.dat` pour créer le *data frame* `Tab1` en supposant que le fichier est bien dans le répertoire courant. Sinon il faut préciser le chemin. 

`help(read.table)` fournit la liste des nombreuses options de cette fonction très utile. Les fonctions `read.csv` et `read.csv2` en sont des cas particuliers, c'est-à-dire avec des options spécifiques (caractère séparateur, marque décimale) adaptées aux fichiers lus / écrits par des tableurs en format `.csv`.


Utiliser un éditeur de texte pour créer les quatre fichiers `fic1.txt` à `fic4.txt` ci-dessous  en respectant scrupuleusement la ponctuation.

			5,2.5,3.8 
			8,3.2,3.4 
			12,4.6,5 

N.B. séparateur par caractère de tabulation pour le fichier `fic2.txt`

			5       2.5     3.8  
			8       3.2     3.4  
			12      4.6     5  

			X1;X2;X3  
			5;2.5;3.8  
			8;3.2;3.4  
			12;4.6;5	
            
			5;2,5;3,8  
			8;3,2;3,4  
			12;4,6;5 

Comparer les modes de lecture de fichiers en fonction du type, des séparateurs et de la présence de la première ligne de noms des variables.

In [148]:
fic1=read.table("fic1.csv",sep=",")
fic1

V1 V2  V3 
1  5 2.5 3.8
2  8 3.2 3.4
3 12 4.6 5.0

In [149]:
fic1b=read.csv("fic1.csv")
fic1b

X5 X2.5 X3.8
1  8 3.2  3.4 
2 12 4.6  5.0

In [150]:
fic1b=read.csv("fic1.csv",header=FALSE)
fic1b

V1 V2  V3 
1  5 2.5 3.8
2  8 3.2 3.4
3 12 4.6 5.0

**Questions**

Importer les fichiers {\tt fic2.txt}, {\tt fic3.txt} et {\tt fic4.txt}.

**Réponses**

In [156]:
fic2 = read.table("fic2.csv")
fic3 = read.table("fic3.csv",header=T,sep=";")
fic4 = read.table("fic4.csv",sep=";",dec=",")

### 4.2 Exportation d'objets R
Ecriture dans un fichier et traces des exécutions. 

In [157]:
A=seq(1,10,l=50)
write.table(A,"A.txt")
sink("A2.txt")  # Début, ouverture du fichier

In [158]:
A;summary(A)

[1]  1.000000  1.183673  1.367347  1.551020  1.734694  1.918367  2.102041
 [8]  2.285714  2.469388  2.653061  2.836735  3.020408  3.204082  3.387755
[15]  3.571429  3.755102  3.938776  4.122449  4.306122  4.489796  4.673469
[22]  4.857143  5.040816  5.224490  5.408163  5.591837  5.775510  5.959184
[29]  6.142857  6.326531  6.510204  6.693878  6.877551  7.061224  7.244898
[36]  7.428571  7.612245  7.795918  7.979592  8.163265  8.346939  8.530612
[43]  8.714286  8.897959  9.081633  9.265306  9.448980  9.632653  9.816327
[50] 10.000000

   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
   1.00    3.25    5.50    5.50    7.75   10.00 

In [159]:
sink()  # arrêt et fermeture du fichier
summary(A)

   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
   1.00    3.25    5.50    5.50    7.75   10.00 

### 4.3 Liens avec un tableur
L'échange de fichiers avec un tableur se fait simplement à travers le format `.csv` comme précédemment en faisant attention aux versions américaines dans lesquelles les séparateurs de deux valeurs sont des "," et les marques décimales des "." tandis que dans les version françaises, les séparateurs de valeurs sont des ";" et les marques décimales des ",".

#### Passer d'un tableur à R
- Dans Excel (ou *open office*) :
	 1. Ouvrir le fichier de données,
	 2. Enregistrer le fichier au format `csv` (*Comma Separated Value*) en le spécifiant dans la liste déroulante (Type de fichier). 
     3. Quitter Excel. 

- Dans R: L'importation du fichier de données s'effectue avec la fonction `read.table()`. L'aide en ligne fournit tous les détails sur l'utilisation de cette fonction. On peut en général assurer l'importation avec les 4 arguments: `file, header, sep, dec`:
   - `file`  nom du fichier qui contient les données avec le chemin pour y accéder,
   - `header` (`TRUE` ou `FALSE`): précise si la première ligne contient le titre des colonnes, 
   - `sep`  permet de préciser le caractère qui délimite les colonnes,
   - `dec`  permet de préciser le séparateur décimal.
- N.B. Le chemin pour accéder au fichier est indiqué par des "/" et non par des "\".

#### Retour dans le tableur de données traitées avec R

La fonction `write.table` permet d'envoyer un jeu de données R dans un fichier texte. 

Exemple : exporter le jeu de données `resul.dat` dans un fichier afin de poursuivre son analyse avec Excel. Il suffit de préciser que le séparateur décimal est la virgule et le séparateur le point-virgule.

      write.table(resul.dat,"resul.csv",sep=";",dec=",")

Il existe des packages R permettant d'assurer plus directement ces transferts mais la procédure décrite ici est en général recommandée. Pour plus de détails,  se référer au document **R Data Import/Export** disponible sur le CRAN.